// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_awa-PPJGNwqBRyCBcoZzsoyZkb1kBk',
    appId: '1:507664917828:web:fa62553fc95a4256afe311',
    messagingSenderId: '507664917828',
    projectId: 'petshop-23',
    authDomain: 'petshop-23.firebaseapp.com',
    storageBucket: 'petshop-23.appspot.com',
    measurementId: 'G-RC37WXF6HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdo2z6Er038YkydMnFjywn1JqcuPgj5g',
    appId: '1:507664917828:android:6480448f59cccf52afe311',
    messagingSenderId: '507664917828',
    projectId: 'petshop-23',
    storageBucket: 'petshop-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJYApEWrvwr8fro8s0kANDBnmb2zjJgs',
    appId: '1:507664917828:ios:5bc9ebc28aa7a28bafe311',
    messagingSenderId: '507664917828',
    projectId: 'petshop-23',
    storageBucket: 'petshop-23.appspot.com',
    iosBundleId: 'com.example.dogShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaJYApEWrvwr8fro8s0kANDBnmb2zjJgs',
    appId: '1:507664917828:ios:5bc9ebc28aa7a28bafe311',
    messagingSenderId: '507664917828',
    projectId: 'petshop-23',
    storageBucket: 'petshop-23.appspot.com',
    iosBundleId: 'com.example.dogShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr_awa-PPJGNwqBRyCBcoZzsoyZkb1kBk',
    appId: '1:507664917828:web:7898d726987efeaaafe311',
    messagingSenderId: '507664917828',
    projectId: 'petshop-23',
    authDomain: 'petshop-23.firebaseapp.com',
    storageBucket: 'petshop-23.appspot.com',
    measurementId: 'G-5H0R59EN7J',
  );
}
